### ISSUE TITLE
Typo in manual.html l.1013

### ISSUE THREAD

**Issue by Lythom** [deltaluca/www.napephys.com#1]
In https://github.com/deltaluca/www.napephys.com/blob/gh-pages/help/manual.html#L1013 
I think
The arbiters list on Bodies records all Arbiters that exist making **us** of that Body.
should be
The arbiters list on Bodies records all Arbiters that exist making **use** of that Body.

**Comment by deltaluca** [comment]
Thanks, fixed now.
